# Generated by Django 5.1.6 on 2025-02-19 15:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survivor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('is_infected', models.BooleanField(default=False)),
                ('reports_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Survivors',
                'db_table': 'survivors',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('WATER', 'Water - 4 points'), ('FOOD', 'Food - 3 points'), ('MEDICATION', 'Medication - 2 points'), ('AMMUNITION', 'Ammunition - 1 point')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('survivor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='zssn_app.survivor')),
            ],
            options={
                'verbose_name': 'Inventory',
                'db_table': 'inventory',
            },
        ),
    ]
