# Generated by Django 5.1.6 on 2025-03-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zssn_app', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('survivor', 'item'), name='unique_item_per_survivor'),
        ),
    ]
